FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y install apt-utils ca-certificates
COPY worktips-deb-key.gpg /etc/apt/trusted.gpg.d/worktips.gpg
RUN echo "deb https://deb.worktips.io focal main" > /etc/apt/sources.list.d/worktips.list && \
    apt-get update
